version: '3'

services:
  db:
    image: mongo
    environment:
     - MONGO_URI=tech
    ports:
     - "27017"
  web:
    build: .
    command: ["/bin/sh", "-c","node server.js"]
    volumes:
      - .:/var/node/techscraper
    ports:
      - "3000:8080"
    depends_on:
      - db
