version: '3'

services:
  db:
    image: mongo
    environment:
     - MONGO_INITDB_ROOT_USERNAME=mongoadmin
     - MONGO_INITDB_ROOT_PASSWORD=casper34
    ports:
     - "3306:27017"
  web:
    build: .
    command: ["/bin/sh", "-c","sleep 10 && node server.js"]
    volumes:
      - .:/var/node/techscraper
    ports:
      - "3000:3000"
    depends_on:
      - db
